export const keyTypes = {
    ADMIN_KEY:            "ADMIN_KEY",
    MEMBER_KEY:           "MEMBER_KEY",
    BASIC_KEY:            "BASIC_KEY",
    LOCALIZATION_KEY:     "LOCALIZATION_KEY",
    SERVICE_DATA_KEY:     "SERVICE_DATA_KEY",
    MESH_NETWORK_KEY:     "MESH_NETWORK_KEY",
    MESH_APPLICATION_KEY: "MESH_APPLICATION_KEY",
    MESH_DEVICE_KEY:      "MESH_DEVICE_KEY",
    DEVICE_UART_KEY:      "UART_DEVICE_KEY",
};

export const sphereFeatures : Record<string, SphereFeature_t> = {
    ENERGY_COLLECTION_PERMISSION: "ENERGY_COLLECTION_PERMISSION",
}
